### ISSUE TITLE
Apply CSS to images

### ISSUE THREAD

**Issue by gkarmas** [akbansa/particlejs-images-demo#5]
Hey, first of all, AMAZING. This is exactly what I was looking for.
Second, I am trying to force all images to be in circle instead of rectangle. 
Something like: border-radius: 50%;
But I can't figure it out with images inside the canvas.
Any ideas @akbansa  ?

**Comment by akbansa** [comment]
@gkarmas If you can explain me the use case of doing so, that will be great!
Or if these are static images, better to use round images itself instead of modifying with css

**Comment by tikmaster** [comment]
Yeah I ended up converting all png images to rounded images :) But it would be nice to figure out a way of doing this dynamically.
For example if I could add shadow behind each image via css or something similar, that would be great.
Here is what i am working on: https://mantravape.com/images/index.html
Also, it doesn't seem to work with v2 of particles.js - is this a completely modified js ?https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js

**Comment by akbansa** [comment]
@gkarmas you can do this by adding the new style to images. You have to modify the `createSvgImg` function at https://github.com/akbansa/particlejs-images-demo/blob/9b7c4644b12960416facc299c10f6a393e9b6c9f/assets/js/particles.js#L1227
